services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - 'POSTGRES_DB=fullstackecommerce'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
