spring:
  application:
    name: e-commerce
  datasource:
    url: jdbc:postgresql://localhost:5432/fullstackecommerce
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    rest:
      base-path: /api

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type: trace
