spring:
  application:
    name: e-commerce
  datasource:
    url: jdbc:postgresql://localhost:5432/fullstackecommerce
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type: trace
management:
  endpoints:
    web:
      cors:
        allowed-origins: https://localhost:4200
okta:
  oauth2:
    client-id: 0oajmmvh3wtt7XMDR5d7
    issuer: https://dev-52838579.okta.com/oauth2/default
